title: Youchen Shen
logo: /assets/img/headshot_circle.jpg
#description: text below image
description: 
I am a Data Analyst with over 4 years of experience in using data to solve problems. 
I am passionate about collaborating with diverse teams to drive data-driven decisions and creating appealing data visualizations. 
I value self-learning with growth mindset and maintaining data integrity, striving to make a meaningful impact through innovative solutions. 

show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

